import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createClient, Entry, EntryFields } from "contentful";

interface Post {
    title: string;
    body: EntryFields.RichText;
}

interface Props {
    items: Entry<Post>[];
}

const Home: NextPage<Props> = ({ items }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Blog post from contentful</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {items.map((entry) => {
                return (
                    <>
                        <h1>{entry.fields.title}</h1>
                        <div>
                            {entry.fields.body.content.map((content, index) => {
                                return (
                                    <div key={index}>
                                        {content.content?.map(
                                            (subContent, subIndex) => {
                                                return (
                                                    <div key={subIndex}>
                                                        {subContent.value}
                                                    </div>
                                                );
                                            }
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </>
                );
            })}
        </div>
    );
};

export async function getStaticProps() {
    const client = createClient({
        space: process.env.CF_SPACE_ID || "",
        environment: process.env.CF_ENVIRONMENT,
        accessToken: process.env.CF_DELIVERY_API || "",
    });

    let entries = await client.getEntries();

    return {
        props: {
            items: entries.items,
        },
    };
}

export default Home;
