import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createClient, Entry, EntryFields } from "contentful";
import PostTile from "../components/PostTile";
import { useEffect, useState } from "react";
import { themeChange } from "theme-change";
import ThemeDropdown from "../components/ThemeDropdown";

interface Post {
    title: string;
    body: EntryFields.RichText;
}

interface Props {
    items: Entry<Post>[];
}

const Home: NextPage<Props> = ({ items }) => {
    useEffect(() => {
        themeChange(false);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Blog post from contentful</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="text-center flex container justify-between mx-auto lg:w-3/4">
                <h1 className="text-5xl my-16 text-primary">
                    <a href="/">My Blog</a>
                </h1>
                <ThemeDropdown className="self-center" />
            </header>
            <div className="container mx-auto lg:w-3/4">
                {items.map((entry, index) => {
                    return <PostTile key={index} entry={entry} />;
                })}
            </div>
            <footer className="text-center my-12">
                &copy; {new Date().getFullYear()} Mihai Ionut Vilcu
            </footer>
        </div>
    );
};

export async function getStaticProps() {
    const client = createClient({
        space: process.env.CF_SPACE_ID || "",
        environment: process.env.CF_ENVIRONMENT,
        accessToken: process.env.CF_DELIVERY_API || "",
    });

    let entries = await client.getEntries();

    return {
        props: {
            items: entries.items,
        },
    };
}

export default Home;
