import Head from "next/head";
import React, { useEffect } from "react";
import { themeChange } from "theme-change";
import ThemeDropdown from "../components/ThemeDropdown";
import Link from "next/link";

interface Props {}

export default function MainLayout({
    children,
}: React.PropsWithChildren<Props>) {
    useEffect(() => {
        themeChange(false);
    }, []);

    return (
        <div>
            <Head>
                <title>My Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="text-center flex container justify-between mx-auto lg:w-3/4">
                <h1 className="text-5xl my-16 text-primary">
                    <Link href="/">
                        <a>My Blog</a>
                    </Link>
                </h1>
                <ThemeDropdown className="self-center" />
            </header>
            <div className="container mx-auto lg:w-3/4">{children}</div>
            <footer className="text-center my-12">
                &copy; {new Date().getFullYear()} Mihai Ionut Vilcu
            </footer>
        </div>
    );
}
